# Build settings

source: .
destination: ./_site
markdown: kramdown
permalinks: pretty
safe: true
markdown_ext: md

##############################################################################

# Site settings

name: Annodoc
homeurl: ""
editurl: "https://github.com/spyysalo/s800-revision-docs/edit/master"
issueurl: "https://github.com/spyysalo/s800-revision-docs/issues"

##############################################################################

# Collection settings

collections:
  type:
    output: true
